const mongoose = require("mongoose")
const locationSchema  = mongoose.Schema({
    job_id:{
        type:String,
        required:true
    },
    building:{
        type:String,
        //enum:['apartment','colony'],
        required:true
    },
    level:{
        type:String,
        //enum:['ground','first'],
        required:true
    },
    location:{
        type:String,
        required:true
    },
    inspectTo:{
        type:String,
        //enum:['location','item'],
        required:true
    },
    inspect:{
        type:Object,
        required:true
    },
    is_suspect_asbestos:{
        type:Boolean,
        default:false
    },
    suspect_asbestos:{
        type:Object,
        required:false
    },
    is_priority_assessment:{
        type:Boolean,
        default:false
    },
    priority_assessment:{
        type:Object,
        required:false
    },
    recomandation:{
        type:String,
        required:true
    },
    additional_comments:{
        type:String,
        required:true
    },
    status:{
        type:String,
        required:true
    },
    added_date:{
        type:Date,
        default:Date.now()
    },
    added_by:{
        type:String,
        required:true
    },
    edit_date:{
        type:Date,
        default:Date.now()
    },
    edit_by:{
        type:String,
        required:false
    }
})
module.exports = mongoose.model("Inspection",locationSchema)